-- =====================================================================================
--  V26 : AI 통합 대시보드 — 업로드 문서 · 버전  (REQ_20260910 요구 6·8, B4)
--
--  [배경]
--  작업자가 정해진 엑셀 포맷으로 가공 결과를 올리면 그 엑셀로 차트·표를 만들어 회의에 쓴다.
--  올린 문서는 서버에 저장하고 버전을 관리한다. 대시보드에서 문서·버전을 골라 결과를 보고,
--  시스템 관리에서는 목록만 본다.
--
--  [설계]
--  문서(tb_dash_upload_doc) 1 : N 버전(tb_dash_upload_ver). 파일 자체는 DB 에 넣지 않고
--  storage_path(API 서버 로컬 또는 NAS) 로 가리킨다. 파싱 결과는 정규화 JSON(parse_json) 으로
--  버전 행에 함께 둔다 — 화면은 이 JSON 만으로 그리므로 원본을 다시 읽지 않는다.
--  "삭제" 는 del_flg 로 숨긴다(요구 8 의 시스템 관리는 목록만, Q4 삭제 정책 미확정). 버전은 지우지 않는다.
--  설계 원칙 7항(보고서 문서 저장 안 함)과 다른 것이다 — 이것은 사용자가 올린 원본 자료지 보고서 산출물이 아니다.
--
--  [이름 관례]  del_yn → del_flg, file_name → file_nm, size_bytes → file_size, parse_state → parse_state_cd
--  상태 코드는 CHECK 대신 공통코드 그룹(DASH_UPLOAD_PARSE) + tb_sys_code_ref 등록 (기준 DDL 방식).
--
--  [적용]
--  docker exec -e PGPASSWORD=dwje_local dwje-pg psql -U dwje_local -d dwjedb -v ON_ERROR_STOP=1 -f V26__dash_upload_doc.sql
--  두 번 실행해도 안전하다.
-- =====================================================================================

-- 1. 문서 -------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS ax.tb_dash_upload_doc (
    doc_id      bigint            GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title       varchar(200)      NOT NULL,
    memo        varchar(1000),
    latest_ver  integer           NOT NULL DEFAULT 0,     -- 0 = 아직 버전 없음. 버전 등록과 같은 트랜잭션에서 올린다
    del_flg     common.d_yn       NOT NULL DEFAULT 'N',
    ins_date    timestamptz       NOT NULL DEFAULT now(),
    ins_user    common.d_user_id,
    upd_date    timestamptz       NOT NULL DEFAULT now(),
    upd_user    common.d_user_id,

    CONSTRAINT ck_dash_upload_doc_ver CHECK (latest_ver >= 0)
);
CREATE INDEX IF NOT EXISTS ix_dash_upload_doc_live ON ax.tb_dash_upload_doc (upd_date DESC) WHERE del_flg = 'N';

COMMENT ON TABLE  ax.tb_dash_upload_doc            IS 'AI 통합 대시보드 업로드 문서 — 작업자가 올린 엑셀의 묶음 단위. 버전은 tb_dash_upload_ver';
COMMENT ON COLUMN ax.tb_dash_upload_doc.latest_ver IS '최신 버전 번호. tb_dash_upload_ver 의 max(ver) 와 같아야 하며 버전 등록 트랜잭션에서 함께 갱신한다';
COMMENT ON COLUMN ax.tb_dash_upload_doc.del_flg    IS 'Y = 목록에서 숨김. 버전·파일은 지우지 않는다';
COMMENT ON COLUMN ax.tb_dash_upload_doc.ins_user   IS '최초 업로더 (시스템 관리 목록의 createdBy)';

-- 2. 버전 -------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS ax.tb_dash_upload_ver (
    doc_id          bigint            NOT NULL,
    ver             integer           NOT NULL,
    file_nm         varchar(300)      NOT NULL,   -- 업로드 당시 원본 파일명
    storage_path    varchar(500)      NOT NULL,   -- 서버 저장 경로 (app.upload.dir/{docId}/{ver}/원본명 또는 NAS)
    file_size       bigint            NOT NULL,
    sha256          char(64)          NOT NULL,   -- 원본 해시 (무결성·중복 확인)
    parse_state_cd  varchar(30)       NOT NULL,   -- 공통코드 DASH_UPLOAD_PARSE (OK | WARN | FAIL)
    parse_json      jsonb,                        -- 정규화 결과 { sheets:[{title,chartType,x,series[],rows[]}] }
    warning_json    jsonb,                        -- 파싱 경고 목록
    ins_date        timestamptz       NOT NULL DEFAULT now(),   -- uploadedAt
    ins_user        common.d_user_id,                           -- uploadedBy

    CONSTRAINT pk_dash_upload_ver PRIMARY KEY (doc_id, ver),
    CONSTRAINT fk_dash_upload_ver_doc
        FOREIGN KEY (doc_id) REFERENCES ax.tb_dash_upload_doc(doc_id) ON DELETE CASCADE,
    CONSTRAINT ck_dash_upload_ver_no   CHECK (ver >= 1),
    CONSTRAINT ck_dash_upload_ver_size CHECK (file_size >= 0)
);

COMMENT ON TABLE  ax.tb_dash_upload_ver                IS '업로드 문서 버전 — 파일 1개 = 버전 1개. 원본은 storage_path, 화면용 데이터는 parse_json';
COMMENT ON COLUMN ax.tb_dash_upload_ver.storage_path   IS '원본 파일 저장 경로. DB 에는 파일을 넣지 않는다';
COMMENT ON COLUMN ax.tb_dash_upload_ver.sha256         IS '원본 SHA-256 (16진 64자). 같은 문서에 같은 해시가 올라오면 API 가 안내할 수 있다';
COMMENT ON COLUMN ax.tb_dash_upload_ver.parse_state_cd IS '파싱 결과. 공통코드 그룹 = DASH_UPLOAD_PARSE (OK=정상, WARN=경고 있음, FAIL=실패 — parse_json 없음)';
COMMENT ON COLUMN ax.tb_dash_upload_ver.parse_json     IS '엑셀을 화면 계약으로 정규화한 결과. 시트별 { title, chartType(line|bar|grouped|donut|table), x, series[], rows[] }';
COMMENT ON COLUMN ax.tb_dash_upload_ver.ins_user       IS '업로더 (uploadedBy). ins_date = uploadedAt';

-- 3. 공통코드 ---------------------------------------------------------------------------
INSERT INTO ax.tb_sys_code_group (group_cd, group_nm, group_desc, use_flg, sort_seq) VALUES
 ('DASH_UPLOAD_PARSE', '업로드 문서 파싱 결과', 'tb_dash_upload_ver.parse_state_cd', 'Y', 95)
ON CONFLICT (group_cd) DO NOTHING;

INSERT INTO ax.tb_sys_code (group_cd, code, code_nm, code_desc, sort_seq, use_flg, ins_user, upd_user) VALUES
 ('DASH_UPLOAD_PARSE', 'OK',   '정상',      '경고 없이 파싱됨',                       1, 'Y', 'V26', 'V26'),
 ('DASH_UPLOAD_PARSE', 'WARN', '경고 있음', '파싱은 됐으나 warning_json 에 경고가 있음', 2, 'Y', 'V26', 'V26'),
 ('DASH_UPLOAD_PARSE', 'FAIL', '실패',      '파싱 실패. parse_json 없음, 원본만 보관',   3, 'Y', 'V26', 'V26')
ON CONFLICT (group_cd, code) DO NOTHING;

INSERT INTO ax.tb_sys_code_ref (target_table, target_column, group_cd, nullable_flg) VALUES
 ('tb_dash_upload_ver', 'parse_state_cd', 'DASH_UPLOAD_PARSE', 'N')
ON CONFLICT (target_table, target_column) DO NOTHING;
