-- =====================================================================================
--  V27 : AOI 판정 분석 — 불량 이미지(NAS 경로) 매핑  (REQ_20260910 요구 9, B4)
--
--  [MES 원천 확인 결과 — 2026-09-10 로컬 dwjedb(MES 복제본) 기준]
--  MES 에 AOI 전용 테이블은 없다. AOI 판정은 mes.tb_pop_label_hist 의 한 행(라벨)이고,
--  설비(eqpt_cd → mes.tb_md_eqpt 의 model_nm/eqpt_nm ILIKE '%AOI%') 로 구분한다.
--  기존 findAoiJudgeStats 가 쓰는 기준과 같다.
--    · AOI 라벨 11,295건 (2025-06-22 ~ 2026-08-13), 그중 defect > 0 인 것 6,949건, 설비 32대
--    · 작업장은 V120 'AOI PACKING (TRAY)' · V140 'AOI PACKING (REEL)' 둘뿐
--    · mes.tb_pop_defect_hist(불량 유형별 이력) 에는 이 두 작업장 행이 **0건** —
--      즉 AOI 불량은 라벨의 defect 수량으로만 있고 "불량 유형 코드" 는 MES 에 없다.
--      (lot_no·serial_no 만으로 다른 작업장의 불량 이력을 붙이면 다른 공정 행이 섞인다 — 붙이지 말 것)
--  따라서 "불량 id" 는 라벨 키 (plant_cd, wc_cd, lot_no, serial_no) 이고 "날짜" 는 라벨의 ins_date 다.
--
--  [이 테이블의 역할]
--  라벨 1건 ↔ NAS 사진 N장. NAS 경로 규칙 문서가 오기 전에는 이 매핑을 읽어 사진을 찾는다.
--  규칙이 "경로 조합형" 으로 확정되면 서비스가 조합하고, 이 테이블은 실제 존재하는 파일의
--  색인(크기·촬영시각·AOI 가 준 불량 유형) 으로 계속 쓸 수 있다. 그래서 만들어 둔다.
--
--  [키를 문자열 하나로 두지 않는 이유]
--  MES 와 조인할 때 형변환이 없도록 common 도메인 4컬럼으로 저장한다 (설계 원칙 4).
--  API 가 URL 에 쓰는 문자열 id(plant-wc-lot-serial) 는 생성 컬럼 defect_id 로 함께 둔다.
--  mes 스키마로의 물리 FK 는 두지 않는다 (AX → MES 는 논리 관계, 기준 DDL 15절).
--
--  [적용]
--  docker exec -e PGPASSWORD=dwje_local dwje-pg psql -U dwje_local -d dwjedb -v ON_ERROR_STOP=1 -f V27__aoi_defect_image.sql
--  두 번 실행해도 안전하다.
-- =====================================================================================

CREATE TABLE IF NOT EXISTS ax.tb_aoi_defect_image (
    image_id     bigint               GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plant_cd     common.d_plant_cd    NOT NULL,
    wc_cd        common.d_wc_cd       NOT NULL,
    lot_no       common.d_lot_no      NOT NULL,
    serial_no    common.d_lot_serial  NOT NULL,
    defect_id    varchar(60)          GENERATED ALWAYS AS
                     (plant_cd::text || '-' || wc_cd::text || '-' || lot_no::text || '-' || serial_no::text) STORED,
    defect_cd    common.d_defect_cd,                       -- AOI 장비가 준 불량 유형. MES 에는 없으므로 NULL 허용
    seq          smallint             NOT NULL DEFAULT 1,  -- 같은 라벨의 사진 순번(1부터)
    nas_path     varchar(500)         NOT NULL,            -- NAS 루트 아래 상대 또는 절대 경로. API 프록시가 읽는다
    file_size    bigint,
    captured_at  timestamptz,
    ins_date     timestamptz          NOT NULL DEFAULT now(),
    ins_user     common.d_user_id,

    CONSTRAINT uq_aoi_defect_image_seq UNIQUE (plant_cd, wc_cd, lot_no, serial_no, seq),
    CONSTRAINT ck_aoi_defect_image_seq CHECK (seq >= 1),
    CONSTRAINT ck_aoi_defect_image_size CHECK (file_size IS NULL OR file_size >= 0)
);
-- API 는 URL 의 문자열 id 로 찾는다 (GET /quality/aoi/defects/{defectId})
CREATE INDEX IF NOT EXISTS ix_aoi_defect_image_defect_id ON ax.tb_aoi_defect_image (defect_id, seq);
-- 기간 필터·목록의 imageCnt 집계용
CREATE INDEX IF NOT EXISTS ix_aoi_defect_image_captured  ON ax.tb_aoi_defect_image (captured_at);

COMMENT ON TABLE  ax.tb_aoi_defect_image             IS 'AOI 판정 라벨(mes.tb_pop_label_hist 키) ↔ NAS 불량 사진 매핑. MES 에는 AOI 불량 id·사진이 없어 여기서 잇는다';
COMMENT ON COLUMN ax.tb_aoi_defect_image.defect_id   IS '생성 컬럼: plant_cd-wc_cd-lot_no-serial_no (예 PL01-V140-20260803-00313). API 의 defectId';
COMMENT ON COLUMN ax.tb_aoi_defect_image.defect_cd   IS 'AOI 장비가 준 불량 유형 코드(mes.tb_md_defect 와 논리 연결). MES 라벨에는 유형이 없어 NULL 이 보통';
COMMENT ON COLUMN ax.tb_aoi_defect_image.nas_path    IS 'NAS 경로. 브라우저가 직접 읽지 않고 GET /files/aoi-images/{imageId} 프록시가 화이트리스트 루트 아래에서만 읽는다';
COMMENT ON COLUMN ax.tb_aoi_defect_image.captured_at IS 'AOI 촬영 시각. 없으면 라벨의 ins_date(KST 벽시계, timestamp(3)) 를 쓴다';
