-- =====================================================================================
--  덕우전자 AX 시스템 — 스키마 확장 (API 구현 전제)
--
--  배경
--  ----
--  기존 DDL(ai_db_query.sql / mes_db_query.sql / ai_db_vector_query.sql)에는
--  아래 업무를 담을 테이블이 정의되어 있지 않다.
--
--   1) 보고서 "문서 인스턴스"
--      ax.tb_rpt_report 는 보고서 '정의'(어떤 보고서가 있는지)만 담고 있어
--      일일 생산현황 보고(PR-03) · 품질 보고서(QC-03) · 폐기 보고서(RP-06/07)의
--      초안·버전·확정 상태·항목 값·결재선을 저장할 곳이 없다.
--   2) 비가동 이력 (PR-05)
--      설비 정지/재가동 구간과 사유를 담을 테이블이 없다.
--   3) 연간 출하계획 (RP-03)
--   4) 품목 단가 (RP-07 폐기 금액 산정)
--
--  본 스크립트는 위 4개 업무를 위한 최소 확장 테이블을 정의한다.
--  기존 테이블은 변경하지 않으며, 명명 규칙(tb_ 접두, 코드 컬럼 _cd, Y/N 은 common.d_yn)과
--  감사 컬럼(ins_date/ins_user/upd_date/upd_user) 관례를 그대로 따른다.
--
--  적용 : psql -d dwjedb -f V2__ax_report_extension.sql
-- =====================================================================================

SET search_path TO ax, mes, vec, common, public;

-- =====================================================================================
-- 1. 보고서 문서 인스턴스
-- =====================================================================================

/* 보고서 문서 (초안 → 임시저장 → 확정/반려) */
CREATE TABLE IF NOT EXISTS ax.tb_rpt_doc (
    doc_id              bigint          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doc_no              varchar(30),
    report_id           varchar(30)     REFERENCES ax.tb_rpt_report (report_id),
    form_id             integer         REFERENCES ax.tb_rpt_form (form_id),
    doc_kind_cd         varchar(30)     NOT NULL,
    title               varchar(200),
    target_date         date,
    period_from         timestamptz,
    period_to           timestamptz,
    occur_date          date,
    version_no          integer         NOT NULL DEFAULT 1,
    state_cd            varchar(30)     NOT NULL DEFAULT 'DRAFT',
    plant_cd            common.d_plant_cd,
    wc_cd               common.d_wc_cd,
    lot_no              common.d_lot_no,
    item_cd             common.d_item_cd,
    product_id          integer         REFERENCES ax.tb_prod_product (product_id),
    customer_id         integer         REFERENCES ax.tb_prod_customer (customer_id),
    disclosure_policy   varchar(200),
    correction_cnt      integer         NOT NULL DEFAULT 0,
    summary_json        jsonb,
    due_date            date,
    generated_at        timestamptz     NOT NULL DEFAULT now(),
    generated_by        common.d_user_id,
    confirmed_at        timestamptz,
    confirmed_by        common.d_user_id,
    rejected_at         timestamptz,
    rejected_by         common.d_user_id,
    reject_reason       varchar(500),
    remark              varchar(1000),
    del_flg             common.d_yn     NOT NULL DEFAULT 'N',
    ins_date            timestamptz     NOT NULL DEFAULT now(),
    ins_user            common.d_user_id,
    upd_date            timestamptz     NOT NULL DEFAULT now(),
    upd_user            common.d_user_id
);

COMMENT ON TABLE  ax.tb_rpt_doc              IS '보고서 문서 인스턴스 — 일일 생산현황·품질·폐기 보고서의 초안/버전/상태를 관리';
COMMENT ON COLUMN ax.tb_rpt_doc.doc_kind_cd  IS '문서 구분 (RPT_DOC_KIND) — DAILY / QUALITY / SCRAP';
COMMENT ON COLUMN ax.tb_rpt_doc.state_cd     IS '문서 상태 (RPT_DOC_STATE) — DRAFT / SAVED / CONFIRMED / REJECTED / PUBLISHED';
COMMENT ON COLUMN ax.tb_rpt_doc.doc_no       IS '화면 표기 문서번호 (폐기 보고서 등). 자동 채번';
COMMENT ON COLUMN ax.tb_rpt_doc.correction_cnt IS 'AI 초안 대비 사람이 보정한 항목 수';

CREATE INDEX IF NOT EXISTS ix_tb_rpt_doc_kind_date ON ax.tb_rpt_doc (doc_kind_cd, target_date DESC);
CREATE INDEX IF NOT EXISTS ix_tb_rpt_doc_state     ON ax.tb_rpt_doc (state_cd, generated_at DESC);
CREATE UNIQUE INDEX IF NOT EXISTS uq_tb_rpt_doc_no ON ax.tb_rpt_doc (doc_no) WHERE doc_no IS NOT NULL;

/* 보고서 항목 값 — 양식 항목(ax.tb_rpt_form_field) 단위 값과 기입 출처 */
CREATE TABLE IF NOT EXISTS ax.tb_rpt_doc_field (
    doc_id          bigint          NOT NULL REFERENCES ax.tb_rpt_doc (doc_id) ON DELETE CASCADE,
    field_seq       smallint        NOT NULL,
    section_cd      varchar(30)     NOT NULL DEFAULT 'BODY',
    field_nm        varchar(100)    NOT NULL,
    field_code      varchar(50),
    field_value     text,
    origin_cd       varchar(30)     NOT NULL DEFAULT 'MANUAL',
    is_corrected    boolean         NOT NULL DEFAULT false,
    blind_field_key varchar(30)     REFERENCES ax.tb_sys_data_field (field_key),
    remark          varchar(300),
    CONSTRAINT pk_tb_rpt_doc_field PRIMARY KEY (doc_id, field_seq)
);

COMMENT ON TABLE  ax.tb_rpt_doc_field           IS '보고서 항목 값 — 자동 기입/사람 보정 구분 포함';
COMMENT ON COLUMN ax.tb_rpt_doc_field.origin_cd IS '기입 출처 (RPT_ORIGIN) — MES / AI / MANUAL';
COMMENT ON COLUMN ax.tb_rpt_doc_field.section_cd IS '섹션 구분 — HEADER / RESULT / CONDITION / CAUSE / TRACE / ACTION / BODY';

/* 보고서 생성·처리 이력 */
CREATE TABLE IF NOT EXISTS ax.tb_rpt_doc_event (
    event_id        bigint          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doc_id          bigint          NOT NULL REFERENCES ax.tb_rpt_doc (doc_id) ON DELETE CASCADE,
    event_at        timestamptz     NOT NULL DEFAULT now(),
    event_type_cd   varchar(30)     NOT NULL,
    detail          varchar(500),
    actor_user_id   common.d_user_id,
    actor_dept_nm   varchar(50)
);

COMMENT ON TABLE  ax.tb_rpt_doc_event                IS '보고서 생성·보정·확정·반려 이력';
COMMENT ON COLUMN ax.tb_rpt_doc_event.event_type_cd  IS '이벤트 (RPT_DOC_EVENT) — GENERATE / REGENERATE / CORRECT / SAVE / CONFIRM / REJECT / COPY / PUBLISH / EXPORT';

/* 증빙 이미지 첨부 */
CREATE TABLE IF NOT EXISTS ax.tb_rpt_doc_image (
    image_id        bigint          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doc_id          bigint          NOT NULL REFERENCES ax.tb_rpt_doc (doc_id) ON DELETE CASCADE,
    image_nm        varchar(200)    NOT NULL,
    nas_path        varchar(1000)   NOT NULL,
    defect_cd       common.d_defect_cd,
    lot_no          common.d_lot_no,
    captured_at     timestamptz,
    attached_at     timestamptz     NOT NULL DEFAULT now(),
    attached_by     common.d_user_id
);

COMMENT ON TABLE ax.tb_rpt_doc_image IS '품질 보고서 증빙 이미지 — NAS 경로 참조';

/* 검토 부서 · 결재선 */
CREATE TABLE IF NOT EXISTS ax.tb_rpt_doc_approval (
    doc_id          bigint          NOT NULL REFERENCES ax.tb_rpt_doc (doc_id) ON DELETE CASCADE,
    appr_seq        smallint        NOT NULL,
    step_cd         varchar(30)     NOT NULL,
    dept_id         integer         REFERENCES ax.tb_sys_dept (dept_id),
    manager_user_id common.d_user_id,
    state_cd        varchar(30)     NOT NULL DEFAULT 'WAITING',
    opinion         varchar(500),
    acted_at        timestamptz,
    due_date        date,
    CONSTRAINT pk_tb_rpt_doc_approval PRIMARY KEY (doc_id, appr_seq)
);

COMMENT ON TABLE  ax.tb_rpt_doc_approval          IS '보고서 검토 부서 · 결재선';
COMMENT ON COLUMN ax.tb_rpt_doc_approval.step_cd  IS '결재 단계 — DRAFT(기안) / REVIEW(검토) / APPROVE(승인)';
COMMENT ON COLUMN ax.tb_rpt_doc_approval.state_cd IS '처리 상태 — WAITING / DONE / REJECTED';

/* 폐기 보고서 상세 행 (MES 전표 + 수기 추가) */
CREATE TABLE IF NOT EXISTS ax.tb_rpt_scrap_row (
    row_id          bigint          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doc_id          bigint          NOT NULL REFERENCES ax.tb_rpt_doc (doc_id) ON DELETE CASCADE,
    voucher_id      varchar(50),
    occur_date      date,
    lot_no          common.d_lot_no,
    item_cd         common.d_item_cd,
    model_cd        varchar(50),
    wc_cd           common.d_wc_cd,
    defect_cd       common.d_defect_cd,
    reason_txt      varchar(200),
    kind_cd         varchar(30)     NOT NULL DEFAULT 'LOSS',
    origin_type_cd  varchar(30)     NOT NULL DEFAULT 'MES',
    qty             numeric(18,6)   NOT NULL DEFAULT 0,
    unit_price      numeric(18,4),
    price_source_cd varchar(30),
    amount          numeric(18,4),
    is_manual       boolean         NOT NULL DEFAULT false,
    remark          varchar(500),
    ins_date        timestamptz     NOT NULL DEFAULT now(),
    ins_user        common.d_user_id
);

COMMENT ON TABLE  ax.tb_rpt_scrap_row                 IS '폐기 보고서 상세 행 — MES 전표 선택분과 수기 추가분';
COMMENT ON COLUMN ax.tb_rpt_scrap_row.kind_cd         IS '폐기 구분 — LOSS(공정 Loss) / DEAD_STOCK(불용재고)';
COMMENT ON COLUMN ax.tb_rpt_scrap_row.origin_type_cd  IS '발생 출처 — MES / MANUAL';
COMMENT ON COLUMN ax.tb_rpt_scrap_row.price_source_cd IS '단가 출처 — MASTER(기준정보) / MANUAL(수기 조정)';

CREATE INDEX IF NOT EXISTS ix_tb_rpt_scrap_row_doc ON ax.tb_rpt_scrap_row (doc_id);

/* 마스킹 해제 요청 */
CREATE TABLE IF NOT EXISTS ax.tb_rpt_unmask_req (
    req_id          bigint          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doc_id          bigint          REFERENCES ax.tb_rpt_doc (doc_id) ON DELETE CASCADE,
    menu_id         varchar(30),
    field_keys      text[]          NOT NULL,
    reason          varchar(500)    NOT NULL,
    state_cd        varchar(30)     NOT NULL DEFAULT 'REQUESTED',
    requested_at    timestamptz     NOT NULL DEFAULT now(),
    requester_id    common.d_user_id NOT NULL,
    requester_dept  varchar(50),
    approver_id     common.d_user_id,
    approved_at     timestamptz,
    approve_note    varchar(500)
);

COMMENT ON TABLE  ax.tb_rpt_unmask_req          IS '마스킹 해제 요청 — 감사 로그와 연계';
COMMENT ON COLUMN ax.tb_rpt_unmask_req.state_cd IS '처리 상태 — REQUESTED / APPROVED / REJECTED';

-- =====================================================================================
-- 2. 비가동 이력 (PR-05)
-- =====================================================================================

CREATE TABLE IF NOT EXISTS ax.tb_prod_downtime (
    downtime_id     bigint          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plant_cd        common.d_plant_cd NOT NULL,
    eqpt_cd         common.d_eqpt_cd  NOT NULL,
    wc_cd           common.d_wc_cd,
    stop_at         timestamptz     NOT NULL,
    resume_at       timestamptz,
    elapsed_min     integer,
    reason_cd       varchar(30),
    remark          varchar(500),
    is_registered   boolean         NOT NULL DEFAULT false,
    detected_by_cd  varchar(30)     NOT NULL DEFAULT 'IOT',
    agent_reason_cd varchar(30),
    agent_confidence numeric(5,4),
    agent_basis     varchar(300),
    registered_at   timestamptz,
    registered_by   common.d_user_id,
    ins_date        timestamptz     NOT NULL DEFAULT now(),
    ins_user        common.d_user_id,
    upd_date        timestamptz     NOT NULL DEFAULT now(),
    upd_user        common.d_user_id,
    CONSTRAINT ck_tb_prod_downtime_period CHECK (resume_at IS NULL OR resume_at >= stop_at)
);

COMMENT ON TABLE  ax.tb_prod_downtime                  IS '설비 비가동 이력 — IoT 자동 감지분과 사람이 등록한 사유';
COMMENT ON COLUMN ax.tb_prod_downtime.reason_cd        IS '비가동 사유 (DOWN_REASON 공통코드)';
COMMENT ON COLUMN ax.tb_prod_downtime.is_registered    IS '사유 등록 여부 — false 면 미등록(사유 미입력) 건';
COMMENT ON COLUMN ax.tb_prod_downtime.agent_reason_cd  IS 'Agent 가 제안한 사유 후보 (채택 전)';
COMMENT ON COLUMN ax.tb_prod_downtime.detected_by_cd   IS '감지 출처 — IOT / MES / MANUAL';

CREATE INDEX IF NOT EXISTS ix_tb_prod_downtime_eqpt ON ax.tb_prod_downtime (plant_cd, eqpt_cd, stop_at DESC);
CREATE INDEX IF NOT EXISTS ix_tb_prod_downtime_stop ON ax.tb_prod_downtime (stop_at DESC);

-- =====================================================================================
-- 3. 연간 출하계획 (RP-03)
-- =====================================================================================

CREATE TABLE IF NOT EXISTS ax.tb_prod_ship_plan (
    plan_id         bigint          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_year       smallint        NOT NULL,
    plan_month      smallint        NOT NULL,
    product_id      integer         NOT NULL REFERENCES ax.tb_prod_product (product_id) ON DELETE CASCADE,
    customer_id     integer         REFERENCES ax.tb_prod_customer (customer_id),
    plan_qty        numeric(18,6)   NOT NULL DEFAULT 0,
    unit_price      numeric(18,4),
    plan_amount     numeric(18,4),
    actual_qty      numeric(18,6),
    remark          varchar(300),
    ins_date        timestamptz     NOT NULL DEFAULT now(),
    ins_user        common.d_user_id,
    upd_date        timestamptz     NOT NULL DEFAULT now(),
    upd_user        common.d_user_id,
    CONSTRAINT uq_tb_prod_ship_plan UNIQUE (plan_year, plan_month, product_id),
    CONSTRAINT ck_tb_prod_ship_plan_month CHECK (plan_month BETWEEN 1 AND 12)
);

COMMENT ON TABLE  ax.tb_prod_ship_plan             IS '연간·월별 출하계획 — 데이터 접근 항목 plan / price 대상';
COMMENT ON COLUMN ax.tb_prod_ship_plan.plan_amount IS '계획 금액 = 계획 수량 × 단가 (price 권한 필요)';

-- =====================================================================================
-- 4. 품목 단가 (RP-07 폐기 금액 산정)
-- =====================================================================================

CREATE TABLE IF NOT EXISTS ax.tb_prod_item_price (
    plant_cd        common.d_plant_cd NOT NULL,
    item_cd         common.d_item_cd  NOT NULL,
    valid_from      date            NOT NULL,
    unit_price      numeric(18,4)   NOT NULL,
    price_kind_cd   varchar(30)     NOT NULL DEFAULT 'COST',
    currency_cd     varchar(3)      NOT NULL DEFAULT 'KRW',
    remark          varchar(300),
    ins_date        timestamptz     NOT NULL DEFAULT now(),
    ins_user        common.d_user_id,
    CONSTRAINT pk_tb_prod_item_price PRIMARY KEY (plant_cd, item_cd, valid_from, price_kind_cd)
);

COMMENT ON TABLE  ax.tb_prod_item_price               IS '품목 단가 기준정보 — 폐기 금액·원가 산정 기준 (price 권한 대상)';
COMMENT ON COLUMN ax.tb_prod_item_price.price_kind_cd IS '단가 구분 — COST(원가) / PROCESS(가공비) / SALE(판매가)';

-- =====================================================================================
-- 5. 확장 테이블용 공통코드 등록
-- =====================================================================================

INSERT INTO ax.tb_sys_code_group (group_cd, group_nm, sort_seq) VALUES
 ('RPT_DOC_KIND','보고서 문서 구분',85),
 ('RPT_DOC_STATE','보고서 문서 상태',86),
 ('RPT_DOC_EVENT','보고서 처리 이벤트',87),
 ('RPT_ORIGIN','보고서 항목 기입 출처',88),
 ('RPT_APPR_STEP','결재 단계',89),
 ('SCRAP_KIND','폐기 구분',93),
 ('SCRAP_ORIGIN','폐기 발생 출처',94),
 ('PRICE_SOURCE','단가 출처',95),
 ('PRICE_KIND','단가 구분',96),
 ('DOWN_REASON','비가동 사유',97),
 ('DOWN_DETECT','비가동 감지 출처',98),
 ('UNMASK_STATE','마스킹 해제 요청 상태',99)
ON CONFLICT (group_cd) DO NOTHING;

INSERT INTO ax.tb_sys_code (group_cd, code, code_nm, sort_seq) VALUES
 ('RPT_DOC_KIND','DAILY','일일 생산현황 보고',1),
 ('RPT_DOC_KIND','QUALITY','품질 보고서',2),
 ('RPT_DOC_KIND','SCRAP','폐기 보고서',3),

 ('RPT_DOC_STATE','DRAFT','초안',1),
 ('RPT_DOC_STATE','SAVED','임시 저장',2),
 ('RPT_DOC_STATE','CONFIRMED','확정',3),
 ('RPT_DOC_STATE','REJECTED','반려',4),
 ('RPT_DOC_STATE','PUBLISHED','발행',5),

 ('RPT_DOC_EVENT','GENERATE','초안 생성',1),
 ('RPT_DOC_EVENT','REGENERATE','초안 재생성',2),
 ('RPT_DOC_EVENT','CORRECT','항목 보정',3),
 ('RPT_DOC_EVENT','SAVE','임시 저장',4),
 ('RPT_DOC_EVENT','CONFIRM','확정',5),
 ('RPT_DOC_EVENT','REJECT','반려',6),
 ('RPT_DOC_EVENT','COPY','복제',7),
 ('RPT_DOC_EVENT','PUBLISH','발행',8),
 ('RPT_DOC_EVENT','EXPORT','출력',9),

 ('RPT_ORIGIN','MES','MES 자동 기입',1),
 ('RPT_ORIGIN','AI','AI 생성',2),
 ('RPT_ORIGIN','MANUAL','수기 입력',3),

 ('RPT_APPR_STEP','DRAFT','기안',1),
 ('RPT_APPR_STEP','REVIEW','검토',2),
 ('RPT_APPR_STEP','APPROVE','승인',3),

 ('SCRAP_KIND','LOSS','공정 Loss',1),
 ('SCRAP_KIND','DEAD_STOCK','불용재고',2),

 ('SCRAP_ORIGIN','MES','MES 전표',1),
 ('SCRAP_ORIGIN','MANUAL','수기 추가',2),

 ('PRICE_SOURCE','MASTER','기준정보 단가',1),
 ('PRICE_SOURCE','MANUAL','수기 조정',2),

 ('PRICE_KIND','COST','원가',1),
 ('PRICE_KIND','PROCESS','가공비',2),
 ('PRICE_KIND','SALE','판매가',3),

 ('DOWN_REASON','CHANGEOVER','금형 교체',1),
 ('DOWN_REASON','BREAKDOWN','설비 고장',2),
 ('DOWN_REASON','MATERIAL','자재 대기',3),
 ('DOWN_REASON','QUALITY','품질 이상 조치',4),
 ('DOWN_REASON','PM','예방 보전',5),
 ('DOWN_REASON','NO_PLAN','생산 계획 없음',6),
 ('DOWN_REASON','BREAK','휴게·식사',7),
 ('DOWN_REASON','ETC','기타',8),

 ('DOWN_DETECT','IOT','IoT 자동 감지',1),
 ('DOWN_DETECT','MES','MES 실적 기반',2),
 ('DOWN_DETECT','MANUAL','수기 등록',3),

 ('UNMASK_STATE','REQUESTED','요청',1),
 ('UNMASK_STATE','APPROVED','승인',2),
 ('UNMASK_STATE','REJECTED','반려',3)
ON CONFLICT (group_cd, code) DO NOTHING;

-- 코드 정합성 검사 대상 등록
INSERT INTO ax.tb_sys_code_ref (target_table, target_column, group_cd, nullable_flg) VALUES
 ('tb_rpt_doc','doc_kind_cd','RPT_DOC_KIND','N'),
 ('tb_rpt_doc','state_cd','RPT_DOC_STATE','N'),
 ('tb_rpt_doc_event','event_type_cd','RPT_DOC_EVENT','N'),
 ('tb_rpt_doc_field','origin_cd','RPT_ORIGIN','N'),
 ('tb_rpt_doc_approval','step_cd','RPT_APPR_STEP','N'),
 ('tb_rpt_scrap_row','kind_cd','SCRAP_KIND','N'),
 ('tb_rpt_scrap_row','origin_type_cd','SCRAP_ORIGIN','N'),
 ('tb_rpt_scrap_row','price_source_cd','PRICE_SOURCE','Y'),
 ('tb_prod_item_price','price_kind_cd','PRICE_KIND','N'),
 ('tb_prod_downtime','reason_cd','DOWN_REASON','Y'),
 ('tb_prod_downtime','detected_by_cd','DOWN_DETECT','N'),
 ('tb_rpt_unmask_req','state_cd','UNMASK_STATE','N')
ON CONFLICT (target_table, target_column) DO NOTHING;

-- =====================================================================================
-- 6. 고객사 LRR 통보 접수 이력 (RP-05)
--    기능명세서 RP-05 데이터 소스 주석의 "고객사 LRR 통보 접수 이력(신규 테이블 필요)" 항목이다.
-- =====================================================================================

CREATE TABLE IF NOT EXISTS ax.tb_qc_lrr_notice (
    notice_id       bigint          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    notice_no       varchar(50),
    customer_id     integer         NOT NULL REFERENCES ax.tb_prod_customer (customer_id),
    product_id      integer         REFERENCES ax.tb_prod_product (product_id),
    plant_cd        common.d_plant_cd,
    lot_no          common.d_lot_no,
    item_cd         common.d_item_cd,
    defect_cd       common.d_defect_cd,
    defect_txt      varchar(200),
    notice_date     date            NOT NULL,
    ship_year       smallint        NOT NULL,
    ship_month      smallint        NOT NULL,
    lrr_qty         numeric(18,6)   NOT NULL DEFAULT 0,
    ship_qty        numeric(18,6),
    state_cd        varchar(30)     NOT NULL DEFAULT 'RECEIVED',
    remark          varchar(500),
    ins_date        timestamptz     NOT NULL DEFAULT now(),
    ins_user        common.d_user_id,
    upd_date        timestamptz     NOT NULL DEFAULT now(),
    upd_user        common.d_user_id,
    CONSTRAINT ck_tb_qc_lrr_notice_month CHECK (ship_month BETWEEN 1 AND 12)
);

COMMENT ON TABLE  ax.tb_qc_lrr_notice           IS '고객사 LRR(라인 불량) 통보 접수 이력 — LRR(%) = LRR Q''ty / Ship Q''ty';
COMMENT ON COLUMN ax.tb_qc_lrr_notice.state_cd  IS '처리 상태 — RECEIVED(접수) / ANALYZING(분석중) / CLOSED(종결)';
COMMENT ON COLUMN ax.tb_qc_lrr_notice.ship_year IS '귀속 출하 연도 — 통보일이 아닌 출하 시점 기준으로 집계한다';

CREATE INDEX IF NOT EXISTS ix_tb_qc_lrr_notice_cust ON ax.tb_qc_lrr_notice (customer_id, ship_year, ship_month);

INSERT INTO ax.tb_sys_code_group (group_cd, group_nm, sort_seq) VALUES
 ('LRR_STATE','LRR 통보 처리 상태',100)
ON CONFLICT (group_cd) DO NOTHING;

INSERT INTO ax.tb_sys_code (group_cd, code, code_nm, sort_seq) VALUES
 ('LRR_STATE','RECEIVED','접수',1),
 ('LRR_STATE','ANALYZING','분석 중',2),
 ('LRR_STATE','CLOSED','종결',3)
ON CONFLICT (group_cd, code) DO NOTHING;

INSERT INTO ax.tb_sys_code_ref (target_table, target_column, group_cd, nullable_flg) VALUES
 ('tb_qc_lrr_notice','state_cd','LRR_STATE','N')
ON CONFLICT (target_table, target_column) DO NOTHING;

-- =====================================================================================
-- 7. 아침회의 일목표 지표 등록 (RP-01 / RP-02)
--    일목표는 별도 테이블을 두지 않고 지표 기준·측정값 체계를 재사용한다.
--    공정별 일목표는 metric_cd = 'PROD_DAY_TARGET' 의 측정값에 wc_cd 를 지정해 적재한다.
-- =====================================================================================

INSERT INTO ax.tb_met_metric_std (
    metric_cd, metric_nm, cat_cd, unit_cd, std_val, warn_val, crit_val,
    window_cd, calc_base, apply_alert, apply_dashboard, apply_report, use_flg
) VALUES
 ('PROD_DAY_TARGET','일 생산 목표','PROD','EA',0,0,0,'DAY_CLOSE',
  '공정별 일 생산 목표 수량. 생산관리팀이 매일 적재하며 아침회의 자료의 일목표 컬럼이 된다.',
  false, false, true, 'Y'),
 ('PROD_ACHIEVE_RATE','일 목표 달성률','PROD','PCT',100,95,90,'DAY_CLOSE',
  '실적 ÷ 일목표 × 100. 아침회의 신호등 판정 기준(정상 100 이상 / 주의 95 이상 / 위험 95 미만).',
  false, true, true, 'Y')
ON CONFLICT (metric_cd) DO NOTHING;
