-- =====================================================================================
--  덕우전자 AX 시스템 — 스키마 확장 : 이관 스키마 드리프트 (SY-15 데이터 연동 이력)
--
--  배경
--  ----
--  ax.tb_sync_map 은 "무엇을 이관할지"를 정의하지만, 원본 MES(MSSQL dbo)와
--  대상(PostgreSQL mes)의 실제 테이블 구성은 그 정의와 무관하게 바뀐다.
--
--    · 정의에 없는 테이블이 생기면  → 아무도 모르는 채 이관되지 않는다
--    · 정의에 있는 테이블이 사라지면 → 해당 작업만 FAIL 로 남고 원인이 묻힌다
--
--  MES_migration_engine 이 배치마다 양쪽 실제 테이블 목록을 tb_sync_map 과 대조해
--  이 테이블에 기록하고, SY-15 화면이 목록을 조회한다.
--
--  기록 방식
--  ---------
--  배치마다 같은 사실을 새 행으로 쌓으면 1년에 수백 건이 되어 읽을 수 없다.
--  같은 드리프트는 UNIQUE 키 기준 1행으로 유지하고 재발견 시 last_seen_at / detect_cnt 만
--  갱신한다. 조치가 끝나 드리프트가 사라지면 엔진이 resolved = true 로 닫는다.
--  따라서 화면이 보여줄 "처리할 목록" 은 resolved = false 인 행이다.
--
--  쓰기 주체 : MES_migration_engine (배치가 직접 JDBC 로 기록한다)
--  읽기 주체 : API — GET /api/v1/sync/schema-drift (No.234)
--              API 는 조회와 수동 해소(No.235)만 하고 판정·기록에 관여하지 않는다.
--
--  기존 DDL(ai_db_query.sql)의 명명 규칙(tb_ 접두, 코드 컬럼 _cd, Y/N 은 common.d_yn)과
--  12절 데이터 연동 테이블(tb_sync_map / tb_sync_job / tb_sync_job_error) 관례를 따른다.
--
--  적용 : psql -d dwjedb -f src/main/resources/db/V3__ax_sync_schema_drift.sql
--  선행 : ai_db_query.sql (ax.tb_sync_map · 공통코드 테이블)
--  재실행 : 안전(멱등)
-- =====================================================================================

SET search_path TO ax, mes, common, public;
SET client_min_messages = WARNING;

BEGIN;

CREATE TABLE IF NOT EXISTS ax.tb_sync_schema_drift (
    drift_id        bigint          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    side_cd         varchar(30)     NOT NULL,
    drift_cd        varchar(30)     NOT NULL,
    db_name         varchar(63)     NOT NULL,
    schema_nm       varchar(63)     NOT NULL,
    table_nm        varchar(63)     NOT NULL,
    map_id          integer         REFERENCES ax.tb_sync_map (map_id),
    detail          varchar(500),
    first_seen_at   timestamptz     NOT NULL DEFAULT now(),
    first_run_id    varchar(30),
    last_seen_at    timestamptz     NOT NULL DEFAULT now(),
    last_run_id     varchar(30),
    detect_cnt      integer         NOT NULL DEFAULT 1,
    resolved        boolean         NOT NULL DEFAULT false,
    resolved_at     timestamptz,
    resolved_by     common.d_user_id,
    resolve_note    varchar(300),
    CONSTRAINT uq_tb_sync_schema_drift UNIQUE (side_cd, db_name, schema_nm, table_nm, drift_cd)
);

COMMENT ON TABLE  ax.tb_sync_schema_drift               IS '이관 스키마 드리프트 — ax.tb_sync_map 의 이관 정의와 원본·대상 DB 의 실제 테이블 목록이 어긋난 사실. 이관 엔진이 배치마다 기록하고 SY-15 화면이 조회한다';
COMMENT ON COLUMN ax.tb_sync_schema_drift.side_cd       IS '발견 위치. 공통코드 그룹 = SYNC_DRIFT_SIDE (SOURCE=원본 MSSQL, TARGET=대상 PostgreSQL)';
COMMENT ON COLUMN ax.tb_sync_schema_drift.drift_cd      IS '드리프트 구분. 공통코드 그룹 = SYNC_DRIFT_KIND (NEW=이관 정의에 없는 신규 테이블, MISSING=정의에는 있으나 실물이 없는 테이블)';
COMMENT ON COLUMN ax.tb_sync_schema_drift.db_name       IS '데이터베이스 명 (원본 MESDB_M, 대상은 PostgreSQL 데이터베이스명)';
COMMENT ON COLUMN ax.tb_sync_schema_drift.schema_nm     IS '스키마 명 (원본 dbo, 대상 mes)';
COMMENT ON COLUMN ax.tb_sync_schema_drift.table_nm      IS '테이블 명. 원본은 대문자, 대상은 소문자 원형 그대로 기록한다';
COMMENT ON COLUMN ax.tb_sync_schema_drift.map_id        IS 'MISSING 인 경우 해당 이관 매핑. NEW 는 매핑이 없으므로 NULL';
COMMENT ON COLUMN ax.tb_sync_schema_drift.detail        IS '조치 안내 문구 (엔진이 생성)';
COMMENT ON COLUMN ax.tb_sync_schema_drift.first_seen_at IS '최초 발견 시각';
COMMENT ON COLUMN ax.tb_sync_schema_drift.first_run_id  IS '최초 발견 배치 실행 식별자 (RUN-yyyyMMdd-HHmm)';
COMMENT ON COLUMN ax.tb_sync_schema_drift.last_seen_at  IS '최종 발견 시각';
COMMENT ON COLUMN ax.tb_sync_schema_drift.last_run_id   IS '최종 발견 배치 실행 식별자';
COMMENT ON COLUMN ax.tb_sync_schema_drift.detect_cnt    IS '누적 발견 횟수. 값이 크면 오래 방치된 드리프트다';
COMMENT ON COLUMN ax.tb_sync_schema_drift.resolved      IS '해소 여부. 다음 배치에서 드리프트가 사라지면 엔진이 자동으로 true 로 닫는다. 화면에서 수동으로 닫을 수도 있다(No.235)';
COMMENT ON COLUMN ax.tb_sync_schema_drift.resolved_by   IS '수동 해소 처리자. 엔진이 자동으로 닫은 경우 NULL';
COMMENT ON COLUMN ax.tb_sync_schema_drift.resolve_note  IS '수동 해소 사유 (예: 이관 대상 아님으로 확인)';

CREATE INDEX IF NOT EXISTS ix_sync_drift_open ON ax.tb_sync_schema_drift (side_cd, drift_cd, last_seen_at DESC) WHERE NOT resolved;
CREATE INDEX IF NOT EXISTS ix_sync_drift_seen ON ax.tb_sync_schema_drift (last_seen_at DESC);

-- ── 공통코드 등록 (ai_db_query.sql 13절과 같은 방식) ──────────────────────────────────
INSERT INTO ax.tb_sys_code_group (group_cd, group_nm, sort_seq) VALUES
 ('SYNC_DRIFT_SIDE','스키마 드리프트 위치',93),
 ('SYNC_DRIFT_KIND','스키마 드리프트 구분',94)
ON CONFLICT (group_cd) DO NOTHING;

INSERT INTO ax.tb_sys_code (group_cd, code, code_nm, sort_seq) VALUES
 ('SYNC_DRIFT_SIDE','SOURCE','원본 (MSSQL)',1),('SYNC_DRIFT_SIDE','TARGET','대상 (PostgreSQL)',2),
 ('SYNC_DRIFT_KIND','NEW','신규 발견',1),('SYNC_DRIFT_KIND','MISSING','유실',2)
ON CONFLICT ON CONSTRAINT pk_tb_sys_code DO NOTHING;

INSERT INTO ax.tb_sys_code_ref (target_table, target_column, group_cd, nullable_flg) VALUES
 ('tb_sync_schema_drift','side_cd','SYNC_DRIFT_SIDE','N'),
 ('tb_sync_schema_drift','drift_cd','SYNC_DRIFT_KIND','N')
ON CONFLICT ON CONSTRAINT pk_tb_sys_code_ref DO NOTHING;

COMMIT;
