-- =====================================================================================
--  V60 : 용어 사전 변경 이력 (2026-10-01)
--
--  [배경]
--  용어 · 유사어 등록 · 수정 · 삭제가 애플리케이션 로그에만 남아 누가 사전을 바꿨는지 알 수 없었다.
--  기획: 07 용어 사전 관리 4.5 · GLS-07 (공통 묶음 M-6).
--
--  [이 파일이 하는 일]
--  ax.tb_gls_change_log 표 1개와 인덱스 2개. 기존 데이터는 건드리지 않는다.
--  용어 · 유사어 표에 FK 를 걸지 않는다 — 용어가 사라져도(유사어는 물리 삭제) 이력은 남아야 한다.
--
--  [순서]
--  이 파일 → API 배포(용어 사전 변경 때 이력 기록).
--
--  [실행]
--  psql -U <user> -d <db> -v ON_ERROR_STOP=1 -f V60__gls_change_log.sql
--  두 번 실행해도 안전하다. 되돌리기는 rollback/V60__down.sql.
-- =====================================================================================

BEGIN;

CREATE TABLE IF NOT EXISTS ax.tb_gls_change_log (
    change_id     bigint GENERATED BY DEFAULT AS IDENTITY,
    changed_at    timestamptz      NOT NULL DEFAULT now(),
    actor_id      common.d_user_id NOT NULL,
    actor_dept_nm varchar(50),
    target_cd     varchar(10)      NOT NULL,
    action_cd     varchar(10)      NOT NULL,
    term_id       integer          NOT NULL,
    variant_id    integer,
    before_json   jsonb,
    after_json    jsonb,
    CONSTRAINT pk_tb_gls_change_log PRIMARY KEY (change_id),
    CONSTRAINT ck_gls_change_target CHECK (target_cd IN ('TERM', 'VARIANT')),
    CONSTRAINT ck_gls_change_action CHECK (action_cd IN ('CREATE', 'UPDATE', 'DELETE', 'RESTORE'))
);

CREATE INDEX IF NOT EXISTS ix_gls_change_term ON ax.tb_gls_change_log (term_id, changed_at DESC);
CREATE INDEX IF NOT EXISTS ix_gls_change_at   ON ax.tb_gls_change_log (changed_at DESC);

COMMENT ON TABLE  ax.tb_gls_change_log               IS '용어 사전 변경 이력 — 용어 · 유사어 등록 · 수정 · 삭제 · 되살림. 쌓기만 하고 고치지 않음';
COMMENT ON COLUMN ax.tb_gls_change_log.change_id     IS '변경 이력 식별자 (PK)';
COMMENT ON COLUMN ax.tb_gls_change_log.changed_at    IS '변경 시각';
COMMENT ON COLUMN ax.tb_gls_change_log.actor_id      IS '수행자 사번';
COMMENT ON COLUMN ax.tb_gls_change_log.actor_dept_nm IS '수행 당시 부서명 스냅샷';
COMMENT ON COLUMN ax.tb_gls_change_log.target_cd     IS '대상 — TERM=공식 용어, VARIANT=유사어';
COMMENT ON COLUMN ax.tb_gls_change_log.action_cd     IS '구분 — CREATE=등록, UPDATE=수정, DELETE=삭제, RESTORE=삭제된 용어 되살림';
COMMENT ON COLUMN ax.tb_gls_change_log.term_id       IS '대상 공식 용어 ID (ax.tb_gls_term 논리 참조, FK 없음)';
COMMENT ON COLUMN ax.tb_gls_change_log.variant_id    IS '대상 유사어 ID (ax.tb_gls_variant 논리 참조, FK 없음). 용어 변경이면 NULL';
COMMENT ON COLUMN ax.tb_gls_change_log.before_json   IS '변경 전 값 (term · term_def · domain_nm 또는 word). 등록이면 NULL';
COMMENT ON COLUMN ax.tb_gls_change_log.after_json    IS '변경 후 값. 삭제면 NULL, 되살림이면 restoredVariants 포함';

COMMIT;
