-- =====================================================================================
--  이메일 인증 (회원가입 · 비밀번호 찾기)
--
--  배경
--  ----
--  · ax.tb_sys_user 에 이메일 컬럼이 없어 본인 확인 수단이 없다.
--    (ax.tb_alm_recipient.email 은 알림 수신 전용이라 가입 전 계정에는 쓸 수 없다)
--  · 인증 코드를 담을 테이블이 필요하다.
--
--  보안 설계
--  --------
--  · 인증 코드는 **해시로만** 저장한다. DB 가 유출돼도 코드를 역산할 수 없다.
--  · 만료(기본 5분) · 시도 횟수(기본 5회) · 재발송 대기 · 일일 발송 상한을 둔다.
--  · 검증에 성공하면 1회용 토큰을 발급하고, 사용 즉시 소멸시킨다(consumed_at).
--  · 비밀번호 찾기는 target_user_id 를 함께 묶어 다른 계정에 재사용할 수 없게 한다.
--
--  적용 : psql -d dwjedb -f V8__email_verification.sql
-- =====================================================================================

SET search_path TO ax, mes, vec, common, public;

-- -------------------------------------------------------------------------------------
-- 1. 계정 이메일
-- -------------------------------------------------------------------------------------
ALTER TABLE ax.tb_sys_user ADD COLUMN IF NOT EXISTS email varchar(200);

COMMENT ON COLUMN ax.tb_sys_user.email IS '계정 이메일 — 회원가입 본인 확인 및 비밀번호 찾기에 사용';

-- 대소문자를 구분하지 않고 중복을 막는다. NULL 은 여러 건 허용한다.
CREATE UNIQUE INDEX IF NOT EXISTS uq_tb_sys_user_email
    ON ax.tb_sys_user (lower(email)) WHERE email IS NOT NULL;

-- -------------------------------------------------------------------------------------
-- 2. 이메일 인증 요청
-- -------------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS ax.tb_sys_email_verify (
    verify_id       bigint          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email           varchar(200)    NOT NULL,
    purpose_cd      varchar(30)     NOT NULL,
    code_hash       varchar(200)    NOT NULL,
    verify_token    varchar(64),
    target_user_id  common.d_user_id,
    expires_at      timestamptz     NOT NULL,
    verified_at     timestamptz,
    consumed_at     timestamptz,
    attempt_cnt     smallint        NOT NULL DEFAULT 0,
    send_result_cd  varchar(30)     NOT NULL DEFAULT 'SENT',
    fail_reason     varchar(300),
    ip_addr         inet,
    ins_date        timestamptz     NOT NULL DEFAULT now(),
    CONSTRAINT ck_tb_sys_email_verify_email CHECK (position('@' IN email) > 1)
);

COMMENT ON TABLE  ax.tb_sys_email_verify                IS '이메일 인증 요청 — 회원가입·비밀번호 찾기 본인 확인';
COMMENT ON COLUMN ax.tb_sys_email_verify.purpose_cd     IS '인증 목적 (EMAIL_VERIFY_PURPOSE) — SIGNUP / PASSWORD_RESET';
COMMENT ON COLUMN ax.tb_sys_email_verify.code_hash      IS '인증 코드 해시. 평문은 저장하지 않는다';
COMMENT ON COLUMN ax.tb_sys_email_verify.verify_token   IS '검증 성공 시 발급하는 1회용 토큰. 사용하면 consumed_at 이 채워진다';
COMMENT ON COLUMN ax.tb_sys_email_verify.target_user_id IS '비밀번호 찾기 대상 계정. 토큰을 다른 계정에 재사용하지 못하게 묶는다';
COMMENT ON COLUMN ax.tb_sys_email_verify.attempt_cnt    IS '코드 검증 시도 횟수. 상한 초과 시 해당 요청을 폐기한다';

CREATE INDEX IF NOT EXISTS ix_tb_sys_email_verify_lookup
    ON ax.tb_sys_email_verify (lower(email), purpose_cd, ins_date DESC);
CREATE UNIQUE INDEX IF NOT EXISTS uq_tb_sys_email_verify_token
    ON ax.tb_sys_email_verify (verify_token) WHERE verify_token IS NOT NULL;

-- -------------------------------------------------------------------------------------
-- 3. 공통코드
-- -------------------------------------------------------------------------------------
INSERT INTO ax.tb_sys_code_group (group_cd, group_nm, sort_seq) VALUES
 ('EMAIL_VERIFY_PURPOSE', '이메일 인증 목적', 16),
 ('EMAIL_SEND_RESULT',    '이메일 발송 결과', 17)
ON CONFLICT (group_cd) DO NOTHING;

INSERT INTO ax.tb_sys_code (group_cd, code, code_nm, code_desc, sort_seq) VALUES
 ('EMAIL_VERIFY_PURPOSE', 'SIGNUP',         '회원가입',      '가입 신청자의 이메일 소유 확인', 1),
 ('EMAIL_VERIFY_PURPOSE', 'PASSWORD_RESET', '비밀번호 찾기', '등록된 계정 이메일로 본인 확인', 2),
 ('EMAIL_SEND_RESULT',    'SENT',           '발송',          NULL, 1),
 ('EMAIL_SEND_RESULT',    'FAIL',           '실패',          NULL, 2),
 ('EMAIL_SEND_RESULT',    'SUPPRESSED',     '발송 억제',     '재발송 대기 또는 일일 상한 초과', 3)
ON CONFLICT (group_cd, code) DO NOTHING;

INSERT INTO ax.tb_sys_code_ref (target_table, target_column, group_cd, nullable_flg) VALUES
 ('tb_sys_email_verify', 'purpose_cd',     'EMAIL_VERIFY_PURPOSE', 'N'),
 ('tb_sys_email_verify', 'send_result_cd', 'EMAIL_SEND_RESULT',    'N')
ON CONFLICT (target_table, target_column) DO NOTHING;
