-- =====================================================================================
--  V31 되돌리기 — 시스템관리 5개 화면 테이블 복원 (2026-09-15)
--
--  V31__drop_removed_screen_tables.sql 이 지운 것을 그대로 되돌린다.
--  구조(테이블·PK·FK·인덱스·IDENTITY·주석) · 공통코드 · 코드 참조 · 메뉴 표시를 복원한다.
--
--  [업무 데이터는 이 파일로 살아나지 않는다]
--  구조만 복원한다. 행은 V31 적용 전에 뜬 덤프에서 되돌린다 —
--      psql -U <user> -d <db> -f drop5_backup.sql    (덤프에 CREATE TABLE 이 함께 있으면
--                                                     이 파일을 돌리지 말고 덤프만 돌린다)
--  덤프가 COPY 만 담고 있다면 이 파일을 먼저 돌려 구조를 만든 뒤 덤프를 적용한다.
--  IDENTITY 시퀀스는 데이터 복원 뒤 다음으로 맞춘다 —
--      SELECT setval(pg_get_serial_sequence('ax.tb_prod_rank_log','log_id'),
--                    coalesce((SELECT max(log_id) FROM ax.tb_prod_rank_log), 1));
--    (tb_ai_pipeline_stage.stage_id · tb_ai_serving_deploy_log.log_id ·
--     tb_met_metric_std_hist.hist_id 도 같은 방식)
--
--  [선행 조건]
--  부모 표가 있어야 FK 가 붙는다 — ax.tb_ai_mask_rule · ax.tb_met_metric_std.
--
--  [적용]
--  psql -U <user> -d <db> -v ON_ERROR_STOP=1 -f rollback/V31__down.sql
--  두 번 실행해도 안전하다.
-- =====================================================================================

-- 1. 테이블 복원 -----------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS ax.tb_ai_mask_rule_column (
    rule_id         integer         NOT NULL,
    target_schema   varchar(63)     NOT NULL,
    target_table    varchar(63)     NOT NULL,
    target_column   varchar(63)     NOT NULL,
    CONSTRAINT pk_tb_ai_mask_rule_column PRIMARY KEY (rule_id, target_schema, target_table, target_column),
    CONSTRAINT tb_ai_mask_rule_column_rule_id_fkey
        FOREIGN KEY (rule_id) REFERENCES ax.tb_ai_mask_rule(rule_id) ON DELETE CASCADE
);
COMMENT ON TABLE ax.tb_ai_mask_rule_column IS '마스킹 규칙 대상 물리 컬럼 — 프로토타입의 item_price, unit_cost, yield_rate, customer_nm, bp_nm, lot_no 등';

CREATE TABLE IF NOT EXISTS ax.tb_ai_pipeline_stage (
    stage_id    integer         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stage_nm    varchar(50)     NOT NULL,
    stage_desc  varchar(200),
    sort_seq    smallint        NOT NULL,
    use_flg     common.d_yn     NOT NULL DEFAULT 'Y'
);
COMMENT ON TABLE ax.tb_ai_pipeline_stage IS 'Master AI 오케스트레이션 파이프라인 단계 — Semantic Parser → Task Planner → DAG Publisher → Agent Bus → Result Evaluator';

CREATE TABLE IF NOT EXISTS ax.tb_ai_serving_deploy_log (
    log_id          bigint          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    log_at          timestamptz     NOT NULL DEFAULT now(),
    service_cd      varchar(20)     NOT NULL,
    action_cd       varchar(30)     NOT NULL,
    profile_id      integer,
    profile_nm      varchar(200)    NOT NULL,
    from_profile_id integer,
    from_profile_nm varchar(200),
    reason          varchar(500),
    actor_user_id   common.d_user_id NOT NULL,
    actor_dept_nm   varchar(50),
    detail_json     jsonb
);
COMMENT ON TABLE  ax.tb_ai_serving_deploy_log            IS 'AI 서비스 버전 전환 이력 — 누가 언제 어떤 버전으로 바꿨고 무엇을 되돌렸는지 (append-only). 보안 감사 제출 대상';
COMMENT ON COLUMN ax.tb_ai_serving_deploy_log.action_cd  IS '동작. 공통코드 그룹 = AI_DEPLOY_ACTION (CANARY=카나리 시작, PROMOTE=전량 배포, ROLLBACK=롤백, RETIRE=폐기, ROUTE=라우팅 변경)';
COMMENT ON COLUMN ax.tb_ai_serving_deploy_log.profile_nm IS '대상 버전 표시명 스냅샷. 프로필이 삭제돼도 이력이 남도록 이름을 함께 저장한다';
CREATE INDEX IF NOT EXISTS ix_deploy_log_at      ON ax.tb_ai_serving_deploy_log (log_at DESC);
CREATE INDEX IF NOT EXISTS ix_deploy_log_service ON ax.tb_ai_serving_deploy_log (service_cd, log_at DESC);

CREATE TABLE IF NOT EXISTS ax.tb_met_metric_std_hist (
    hist_id       bigint        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    metric_id     integer       NOT NULL,
    changed_at    timestamptz   NOT NULL DEFAULT now(),
    field_cd      varchar(30)   NOT NULL,
    before_val    varchar(50),
    after_val     varchar(50),
    changed_by    common.d_user_id NOT NULL,
    actor_dept_nm varchar(50),
    CONSTRAINT tb_met_metric_std_hist_metric_id_fkey
        FOREIGN KEY (metric_id) REFERENCES ax.tb_met_metric_std(metric_id) ON DELETE CASCADE
);
COMMENT ON TABLE  ax.tb_met_metric_std_hist          IS '기준 수치 변경 이력 (append-only). 기준을 바꾸면 즉시 적용되며 소급 재판정은 하지 않는다';
COMMENT ON COLUMN ax.tb_met_metric_std_hist.field_cd IS '변경 항목. 공통코드 그룹 = MET_STD_FIELD (STD=정상 기준, WARN=주의 임계, CRIT=위험 임계, WINDOW=집계 구간, USE=적용 여부)';
CREATE INDEX IF NOT EXISTS ix_met_std_hist_metric ON ax.tb_met_metric_std_hist (metric_id, changed_at DESC);

CREATE TABLE IF NOT EXISTS ax.tb_prod_rank_log (
    log_id        bigint        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    log_at        timestamptz   NOT NULL DEFAULT now(),
    act_cd        varchar(30)   NOT NULL,
    family_id     integer,
    product_id    integer,
    detail        varchar(300)  NOT NULL,
    actor_user_id common.d_user_id NOT NULL,
    actor_dept_nm varchar(50)
);
COMMENT ON TABLE  ax.tb_prod_rank_log        IS '순위 변경 이력 (append-only)';
COMMENT ON COLUMN ax.tb_prod_rank_log.act_cd IS '변경 구분. 공통코드 그룹 = PROD_RANK_ACT (FAMILY=제품군 순위, PRODUCT=제품 순서, RESET=기본 순서 복원)';
CREATE INDEX IF NOT EXISTS ix_prod_rank_log_at ON ax.tb_prod_rank_log (log_at DESC);

-- 2. 공통코드 그룹·코드 복원 --------------------------------------------------------------
INSERT INTO ax.tb_sys_code_group (group_cd, group_nm, use_flg, sort_seq) VALUES
 ('PROD_RANK_ACT',    '순위 변경 구분', 'Y', 31),
 ('MET_STD_FIELD',    '기준 변경 항목', 'Y', 45),
 ('AI_DEPLOY_ACTION', '버전 전환 동작', 'Y', 83)
ON CONFLICT (group_cd) DO NOTHING;

INSERT INTO ax.tb_sys_code (group_cd, code, code_nm, sort_seq, use_flg, ins_user, upd_user) VALUES
 ('AI_DEPLOY_ACTION', 'CANARY',   '카나리 시작',    1, 'Y', 'SEED', 'SEED'),
 ('AI_DEPLOY_ACTION', 'PROMOTE',  '전량 배포',      2, 'Y', 'SEED', 'SEED'),
 ('AI_DEPLOY_ACTION', 'ROLLBACK', '롤백',           3, 'Y', 'SEED', 'SEED'),
 ('AI_DEPLOY_ACTION', 'RETIRE',   '폐기',           4, 'Y', 'SEED', 'SEED'),
 ('AI_DEPLOY_ACTION', 'ROUTE',    '라우팅 변경',    5, 'Y', 'SEED', 'SEED'),
 ('MET_STD_FIELD',    'STD',      '정상 기준',      1, 'Y', 'SEED', 'SEED'),
 ('MET_STD_FIELD',    'WARN',     '주의 임계',      2, 'Y', 'SEED', 'SEED'),
 ('MET_STD_FIELD',    'CRIT',     '위험 임계',      3, 'Y', 'SEED', 'SEED'),
 ('MET_STD_FIELD',    'WINDOW',   '집계 구간',      4, 'Y', 'SEED', 'SEED'),
 ('MET_STD_FIELD',    'USE',      '적용 여부',      5, 'Y', 'SEED', 'SEED'),
 ('PROD_RANK_ACT',    'FAMILY',   '제품군 순위',    1, 'Y', 'SEED', 'SEED'),
 ('PROD_RANK_ACT',    'PRODUCT',  '제품 순서',      2, 'Y', 'SEED', 'SEED'),
 ('PROD_RANK_ACT',    'RESET',    '기본 순서 복원', 3, 'Y', 'SEED', 'SEED')
ON CONFLICT (group_cd, code) DO NOTHING;

-- 3. 코드 참조 복원 ---------------------------------------------------------------------
INSERT INTO ax.tb_sys_code_ref (target_table, target_column, group_cd, nullable_flg) VALUES
 ('tb_ai_serving_deploy_log', 'action_cd',  'AI_DEPLOY_ACTION', 'N'),
 ('tb_ai_serving_deploy_log', 'service_cd', 'AI_SERVICE',       'N'),
 ('tb_met_metric_std_hist',   'field_cd',   'MET_STD_FIELD',    'N'),
 ('tb_prod_rank_log',         'act_cd',     'PROD_RANK_ACT',    'N')
ON CONFLICT DO NOTHING;

-- 4. 화면 되살리기 ----------------------------------------------------------------------
UPDATE ax.tb_sys_menu
   SET use_flg = 'Y',
       upd_date = now(),
       upd_user = 'V31-down'
 WHERE menu_id IN ('sys-rank', 'base-model', 'sys-model-ver', 'ai-agent', 'sys-metric')
   AND use_flg = 'N';
