-- =====================================================================================
--  V32 되돌리기 — 보안 필터링 패턴 표 복원 (2026-09-15)
--
--  V32__drop_ai_mask_rule.sql 이 지운 구조·공통코드·코드 참조를 되돌린다.
--
--  [업무 데이터는 이 파일로 살아나지 않는다 — 덤프를 먼저 돌린다]
--  V31__down.sql 과 같다. ① 적용 전 덤프(CREATE TABLE + 데이터) → ② 이 파일(공통코드·코드 참조).
--  순서를 뒤집으면 덤프의 CREATE TABLE 이 "already exists" 로 실패한다.
--  복원 뒤 IDENTITY 시퀀스를 맞춘다 —
--      SELECT setval(pg_get_serial_sequence('ax.tb_ai_mask_rule','rule_id'),
--                    coalesce((SELECT max(rule_id) FROM ax.tb_ai_mask_rule), 1));
--
--  [선행 조건]
--  부모 표가 있어야 FK 가 붙는다 — ax.tb_prod_customer · ax.tb_sys_data_field.
--  자식 표 ax.tb_ai_mask_rule_column 까지 되살리려면 rollback/V32__down.sql 다음에
--  rollback/V31__down.sql 을 돌린다(그쪽이 이 표를 FK 로 참조한다).
--
--  [적용]
--  psql -U <user> -d <db> -v ON_ERROR_STOP=1 -f rollback/V32__down.sql
--  두 번 실행해도 안전하다.
-- =====================================================================================

-- 1. 표 복원 --------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS ax.tb_ai_mask_rule (
    rule_id      integer          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rule_nm      varchar(50)      NOT NULL,
    field_key    varchar(30),
    mask_type_cd varchar(30)      NOT NULL,
    customer_id  integer,
    policy_desc  varchar(200),
    use_flg      common.d_yn      NOT NULL DEFAULT 'Y',
    ins_date     timestamptz      NOT NULL DEFAULT now(),
    ins_user     common.d_user_id,
    upd_date     timestamptz      NOT NULL DEFAULT now(),
    upd_user     common.d_user_id,
    CONSTRAINT uq_tb_ai_mask_rule_nm UNIQUE (rule_nm),
    CONSTRAINT tb_ai_mask_rule_customer_id_fkey
        FOREIGN KEY (customer_id) REFERENCES ax.tb_prod_customer(customer_id),
    CONSTRAINT tb_ai_mask_rule_field_key_fkey
        FOREIGN KEY (field_key) REFERENCES ax.tb_sys_data_field(field_key)
);
COMMENT ON TABLE  ax.tb_ai_mask_rule              IS '보안 필터링 패턴 — ⑦ 보안 필터링 Agent 가 적용하는 마스킹 규칙 (패턴명 · 대상 필드 · 처리 방식 · 고객사 정책)';
COMMENT ON COLUMN ax.tb_ai_mask_rule.mask_type_cd IS '처리 방식. 공통코드 그룹 = AI_MASK_TYPE (FULL=마스킹, PARTIAL=부분 마스킹, HASH=해시, DROP=제외)';
COMMENT ON COLUMN ax.tb_ai_mask_rule.customer_id  IS '고객사별 정책인 경우의 대상 고객사. NULL 이면 전체 비공개';

-- 2. 공통코드 그룹·코드 복원 --------------------------------------------------------------
INSERT INTO ax.tb_sys_code_group (group_cd, group_nm, use_flg, sort_seq) VALUES
 ('AI_MASK_TYPE', '마스킹 처리 방식', 'Y', 73)
ON CONFLICT (group_cd) DO NOTHING;

INSERT INTO ax.tb_sys_code (group_cd, code, code_nm, sort_seq, use_flg, ins_user, upd_user) VALUES
 ('AI_MASK_TYPE', 'FULL',    '마스킹',      1, 'Y', 'SEED', 'SEED'),
 ('AI_MASK_TYPE', 'PARTIAL', '부분 마스킹', 2, 'Y', 'SEED', 'SEED'),
 ('AI_MASK_TYPE', 'HASH',    '해시',        3, 'Y', 'SEED', 'SEED'),
 ('AI_MASK_TYPE', 'DROP',    '제외',        4, 'Y', 'SEED', 'SEED')
ON CONFLICT (group_cd, code) DO NOTHING;

-- 3. 코드 참조 복원 ---------------------------------------------------------------------
INSERT INTO ax.tb_sys_code_ref (target_table, target_column, group_cd, nullable_flg) VALUES
 ('tb_ai_mask_rule', 'mask_type_cd', 'AI_MASK_TYPE', 'N')
ON CONFLICT DO NOTHING;
