-- =====================================================================================
--  V36 되돌리기 — 당번 · 대리 수신 표 복원 (2026-09-16)
--
--  V36__drop_alert_duty.sql 이 지운 구조·공통코드·코드 참조를 되돌린다.
--  (처음에 V35 로 만들었다가, 같은 날 다른 작업이 V35__alm_engine.sql 을 가져가 V36 으로 옮겼다.)
--
--  [업무 데이터는 이 파일로 살아나지 않는다 — 덤프를 먼저 돌린다]
--  V31__down.sql · V32__down.sql 과 같다. ① 적용 전 덤프(CREATE TABLE + 데이터) →
--  ② 이 파일(공통코드·코드 참조). 순서를 뒤집으면 덤프의 CREATE TABLE 이 "already exists" 로 실패한다.
--  복원 뒤 IDENTITY 시퀀스를 맞춘다 —
--      SELECT setval(pg_get_serial_sequence('ax.tb_alm_duty','duty_id'),
--                    coalesce((SELECT max(duty_id) FROM ax.tb_alm_duty), 1));
--
--  [선행 조건]
--  부모 표가 있어야 FK 가 붙는다 — ax.tb_alm_recip_group · ax.tb_sys_user.
--
--  [적용]
--  psql -U <user> -d <db> -v ON_ERROR_STOP=1 -f rollback/V36__down.sql
--  두 번 실행해도 안전하다.
-- =====================================================================================

-- 1. 표 복원 --------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS ax.tb_alm_duty (
    duty_id         integer          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id        integer          NOT NULL REFERENCES ax.tb_alm_recip_group (group_id) ON DELETE CASCADE,
    from_date       date             NOT NULL,
    to_date         date             NOT NULL,
    main_user_id    common.d_user_id NOT NULL REFERENCES ax.tb_sys_user (user_id),
    sub_user_id     common.d_user_id NOT NULL REFERENCES ax.tb_sys_user (user_id),
    reason_cd       varchar(30)      NOT NULL,
    remark          varchar(300),
    ins_date        timestamptz      NOT NULL DEFAULT now(),
    ins_user        common.d_user_id,
    CONSTRAINT ck_tb_alm_duty_period CHECK (to_date >= from_date),
    CONSTRAINT ck_tb_alm_duty_user   CHECK (main_user_id <> sub_user_id)
);
COMMENT ON TABLE  ax.tb_alm_duty            IS '당번 · 부재 시 대리 수신 — 기간 내에는 담당 대신 대리 수신자에게 발송한다';
COMMENT ON COLUMN ax.tb_alm_duty.reason_cd  IS '사유. 공통코드 그룹 = ALM_DUTY_REASON (ROTATION=주간 정기 당번, LEAVE=연차, TRIP=출장, TRAINING=외부 교육, SICK=병가, ETC=기타)';

CREATE INDEX IF NOT EXISTS ix_alm_duty_period ON ax.tb_alm_duty (group_id, from_date, to_date);

-- 2. 공통코드 그룹·코드 복원 --------------------------------------------------------------
INSERT INTO ax.tb_sys_code_group (group_cd, group_nm, use_flg, sort_seq) VALUES
 ('ALM_DUTY_REASON', '당번 사유', 'Y', 60)
ON CONFLICT (group_cd) DO NOTHING;

INSERT INTO ax.tb_sys_code (group_cd, code, code_nm, sort_seq, use_flg, ins_user, upd_user) VALUES
 ('ALM_DUTY_REASON', 'ROTATION', '주간 정기 당번', 1, 'Y', 'SEED', 'SEED'),
 ('ALM_DUTY_REASON', 'LEAVE',    '연차',           2, 'Y', 'SEED', 'SEED'),
 ('ALM_DUTY_REASON', 'TRIP',     '출장',           3, 'Y', 'SEED', 'SEED'),
 ('ALM_DUTY_REASON', 'TRAINING', '외부 교육',      4, 'Y', 'SEED', 'SEED'),
 ('ALM_DUTY_REASON', 'SICK',     '병가',           5, 'Y', 'SEED', 'SEED'),
 ('ALM_DUTY_REASON', 'ETC',      '기타',           6, 'Y', 'SEED', 'SEED')
ON CONFLICT (group_cd, code) DO NOTHING;

-- 3. 코드 참조 복원 ---------------------------------------------------------------------
INSERT INTO ax.tb_sys_code_ref (target_table, target_column, group_cd, nullable_flg) VALUES
 ('tb_alm_duty', 'reason_cd', 'ALM_DUTY_REASON', 'N')
ON CONFLICT DO NOTHING;
