-- =====================================================================================
--  V73 되돌리기 — 발송 조건 고급 설정 컬럼 6개 · 조건별 승격 표 · 승격 규칙 표 복원 (2026-10-03)
--
--  · 컬럼을 V72 상태로 되살린다(평가 단위 · 평가 주기 · 시간대 무시 · 자동 해제는 NOT NULL + 기본값,
--    지정 시각은 NULL 허용, 메시지 틀은 NULL 허용 + 기본 틀). 되살린 컬럼은 표 맨 뒤에 붙는다.
--  · 보관 표 ax.tb_alm_cond_adv_bak 에 있는 조건은 값을 되돌리고, V73 이후 만든 조건은 기본값으로 둔다.
--  · tb_alm_escalation_rule 표를 원래 정의(V35 · V40 주석, 자동 채번 · 단계 유일 · 수신 그룹 FK)로 다시 만들고
--    보관 표 ax.tb_alm_escalation_rule_bak 에서 행을 되돌린다. 식별자는 원래 값 그대로 넣고 채번을 그 뒤로 맞춘다.
--    대상 수신 그룹이 그사이 지워졌으면 to_group_id 는 비워 둔다(FK).
--  · tb_alm_cond_escalation 표를 원래 키 · FK 로 다시 만들고 보관 표에서 행을 되돌린다
--    (조건 · 승격 단계가 지금도 있는 행만). 승격 규칙 표를 먼저 되살려야 FK 가 걸린다.
--  · 공통코드 정합성 목록에 scope_dim_cd 를 다시 넣는다(ALM_SCOPE_DIM 코드는 V73 이 건드리지 않음).
--  · 보관 표는 남긴다(다시 V73 을 적용할 때 덮어씀).
--
--  [옛 엔진 · 옛 API 로 함께 되돌린다]
--
--  [적용]
--  psql -U <user> -d <db> -v ON_ERROR_STOP=1 -f rollback/V73__down.sql
--  두 번 실행해도 안전하다.
-- =====================================================================================

BEGIN;

-- ── 1. 컬럼 ──────────────────────────────────────────────────────────────────────────
ALTER TABLE ax.tb_alm_cond
    ADD COLUMN IF NOT EXISTS scope_dim_cd      varchar(30)  NOT NULL DEFAULT 'NONE',
    ADD COLUMN IF NOT EXISTS window_time       time,
    ADD COLUMN IF NOT EXISTS eval_interval_sec integer      NOT NULL DEFAULT 60,
    ADD COLUMN IF NOT EXISTS ignore_window_flg common.d_yn  NOT NULL DEFAULT 'N',
    ADD COLUMN IF NOT EXISTS auto_close_flg    common.d_yn  NOT NULL DEFAULT 'N',
    ADD COLUMN IF NOT EXISTS msg_template      text
        DEFAULT '[{{severity}}] {{condNm}} — {{scope}} {{metricNm}} {{value}}{{unit}} ({{op}} {{threshold}}{{unit}}) {{link}}';

DO $$
DECLARE
    v_cnt integer := 0;
BEGIN
    IF to_regclass('ax.tb_alm_cond_adv_bak') IS NOT NULL THEN
        UPDATE ax.tb_alm_cond c
           SET scope_dim_cd      = coalesce(b.scope_dim_cd, 'NONE'),
               eval_interval_sec = coalesce(b.eval_interval_sec, 60),
               window_time       = b.window_time,
               ignore_window_flg = coalesce(b.ignore_window_flg, 'N'),
               auto_close_flg    = coalesce(b.auto_close_flg, 'N'),
               msg_template      = coalesce(b.msg_template, c.msg_template)
          FROM ax.tb_alm_cond_adv_bak b
         WHERE b.cond_id = c.cond_id;
        GET DIAGNOSTICS v_cnt = ROW_COUNT;
    END IF;
    RAISE NOTICE 'V73 되돌리기: 고급 설정 값 되돌림 % 건', v_cnt;
END $$;

COMMENT ON COLUMN ax.tb_alm_cond.scope_dim_cd IS
  '평가 단위. 공통코드 그룹 = ALM_SCOPE_DIM. ''EQPT'' 면 설비마다 따로 판정·따로 억제됨. ''NONE'' 이면 대상 전체를 묶어 값 하나로 판정';
COMMENT ON COLUMN ax.tb_alm_cond.window_time IS
  'window_cd=''ONCE''(지정 시각 1회) 일 때의 시각. 그 밖의 시간대는 공통코드 ALM_WINDOW 의 attr1/attr2 를 사용';
COMMENT ON COLUMN ax.tb_alm_cond.eval_interval_sec IS
  '이 조건을 몇 초마다 평가할지. 엔진 틱(기본 60초)보다 짧게 잡아도 틱 주기가 하한';
COMMENT ON COLUMN ax.tb_alm_cond.ignore_window_flg IS
  '''Y'' 면 유효 시간대 밖에도 발송. 위험(CRIT) 조건을 야간에도 받아야 할 때 사용. 수신자 개인의 야간 미수신(night_recv)은 이 값과 무관하게 지켜짐';
COMMENT ON COLUMN ax.tb_alm_cond.auto_close_flg IS
  '''Y'' 면 값이 정상으로 돌아올 때 tb_alm_alert.resolved_at 을 기록. 확인 처리(ack_state_cd)는 사람 몫 — 자동으로 CLOSED 로 바꾸지 않음';
COMMENT ON COLUMN ax.tb_alm_cond.msg_template IS
  '메시지 틀 — 사용 중지(2026-10-03, 고급 설정 제거). 알림 엔진은 기본 틀 하나로 메시지를 만들고 이 값을 읽지 않음. 빼고 넣으면 기본 틀 문장이 들어감. 컬럼 삭제 예정(값은 보관 표로 옮김)';

-- ── 2. 승격 규칙 표 ──────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS ax.tb_alm_escalation_rule (
    esc_rule_id     integer GENERATED BY DEFAULT AS IDENTITY,
    esc_level       smallint     NOT NULL,
    level_nm        varchar(20)  NOT NULL,
    after_min       integer      NOT NULL,
    to_target_desc  varchar(100) NOT NULL,
    to_group_id     integer,
    severity_filter varchar(30),
    note            varchar(300),
    use_flg         common.d_yn  NOT NULL DEFAULT 'Y',
    CONSTRAINT tb_alm_escalation_rule_pkey PRIMARY KEY (esc_rule_id),
    CONSTRAINT uq_tb_alm_esc_level UNIQUE (esc_level),
    CONSTRAINT tb_alm_escalation_rule_to_group_id_fkey FOREIGN KEY (to_group_id)
        REFERENCES ax.tb_alm_recip_group (group_id)
);
COMMENT ON TABLE  ax.tb_alm_escalation_rule                 IS '미확인 알림 승격 단계 — 1차 30분/파트장, 2차 2시간/팀장, 3차 4시간/경영진';
COMMENT ON COLUMN ax.tb_alm_escalation_rule.esc_rule_id     IS '승격 규칙 식별자 (자동 채번)';
COMMENT ON COLUMN ax.tb_alm_escalation_rule.esc_level       IS '승격 단계 (1=1차, 2=2차, 3=3차). 알림의 esc_level 이 이 값보다 작을 때만 등록';
COMMENT ON COLUMN ax.tb_alm_escalation_rule.level_nm        IS '단계 표시명 (1차·2차·3차). 승격 알림 본문과 발송 사유에 그대로 쓰임';
COMMENT ON COLUMN ax.tb_alm_escalation_rule.after_min       IS '발생 후 이 분(分)이 지나도록 미확인이면 승격한다 (1차 30 · 2차 120 · 3차 240)';
COMMENT ON COLUMN ax.tb_alm_escalation_rule.to_target_desc  IS '승격 대상 표시 문구 (예: 제조팀 파트장). 실제 발송은 to_group_id 로 함';
COMMENT ON COLUMN ax.tb_alm_escalation_rule.to_group_id     IS '승격 알림을 받을 수신 그룹. 비어 있으면 올리지 않고 발송 기록에 실패로 남김';
COMMENT ON COLUMN ax.tb_alm_escalation_rule.severity_filter IS '이 단계로 승격시킬 심각도 제한 (예: CRIT 만 3차 승격). NULL 이면 전 심각도';
COMMENT ON COLUMN ax.tb_alm_escalation_rule.note            IS '이 단계를 두는 이유 메모 (예: 1차 승격 후에도 미확인)';
COMMENT ON COLUMN ax.tb_alm_escalation_rule.use_flg         IS '''Y'' 면 엔진이 이 승격 단계를 적용';

DO $$
DECLARE
    v_cnt integer := 0;
BEGIN
    IF to_regclass('ax.tb_alm_escalation_rule_bak') IS NOT NULL THEN
        INSERT INTO ax.tb_alm_escalation_rule (esc_rule_id, esc_level, level_nm, after_min, to_target_desc,
                                               to_group_id, severity_filter, note, use_flg)
        OVERRIDING SYSTEM VALUE
        SELECT b.esc_rule_id, b.esc_level, b.level_nm, b.after_min, b.to_target_desc,
               CASE WHEN EXISTS (SELECT 1 FROM ax.tb_alm_recip_group g WHERE g.group_id = b.to_group_id)
                    THEN b.to_group_id END,
               b.severity_filter, b.note, b.use_flg
          FROM ax.tb_alm_escalation_rule_bak b
        ON CONFLICT DO NOTHING;
        GET DIAGNOSTICS v_cnt = ROW_COUNT;
    END IF;
    -- 원래 식별자로 넣었으므로 채번을 최댓값 뒤로 맞춘다(행이 없으면 1 부터)
    PERFORM setval(pg_get_serial_sequence('ax.tb_alm_escalation_rule', 'esc_rule_id'),
                   coalesce((SELECT max(esc_rule_id) FROM ax.tb_alm_escalation_rule), 0) + 1, false);
    RAISE NOTICE 'V73 되돌리기: 승격 규칙 되돌림 % 건', v_cnt;
END $$;

-- ── 3. 조건별 승격 표 ────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS ax.tb_alm_cond_escalation (
    cond_id     integer NOT NULL,
    esc_rule_id integer NOT NULL,
    is_on       boolean NOT NULL DEFAULT true,
    CONSTRAINT pk_tb_alm_cond_escalation PRIMARY KEY (cond_id, esc_rule_id),
    CONSTRAINT tb_alm_cond_escalation_cond_id_fkey FOREIGN KEY (cond_id)
        REFERENCES ax.tb_alm_cond (cond_id) ON DELETE CASCADE,
    CONSTRAINT tb_alm_cond_escalation_esc_rule_id_fkey FOREIGN KEY (esc_rule_id)
        REFERENCES ax.tb_alm_escalation_rule (esc_rule_id) ON DELETE CASCADE
);
COMMENT ON TABLE  ax.tb_alm_cond_escalation             IS '발송 조건별 승격 단계 적용 여부';
COMMENT ON COLUMN ax.tb_alm_cond_escalation.cond_id     IS '발송 조건 (tb_alm_cond). 조건이 지워지면 함께 삭제됨';
COMMENT ON COLUMN ax.tb_alm_cond_escalation.esc_rule_id IS '적용할 승격 단계 (tb_alm_escalation_rule)';
COMMENT ON COLUMN ax.tb_alm_cond_escalation.is_on       IS 'true 면 이 조건의 알림을 그 단계로 승격. false 면 시간이 지나도 올리지 않음';

DO $$
BEGIN
    IF to_regclass('ax.tb_alm_cond_escalation_bak') IS NOT NULL THEN
        INSERT INTO ax.tb_alm_cond_escalation (cond_id, esc_rule_id, is_on)
        SELECT b.cond_id, b.esc_rule_id, b.is_on
          FROM ax.tb_alm_cond_escalation_bak b
         WHERE EXISTS (SELECT 1 FROM ax.tb_alm_cond c WHERE c.cond_id = b.cond_id)
           AND EXISTS (SELECT 1 FROM ax.tb_alm_escalation_rule r WHERE r.esc_rule_id = b.esc_rule_id)
        ON CONFLICT (cond_id, esc_rule_id) DO NOTHING;
    END IF;
END $$;

-- ── 4. 공통코드 ──────────────────────────────────────────────────────────────────────
INSERT INTO ax.tb_sys_code_ref (target_table, target_column, group_cd, nullable_flg)
VALUES ('tb_alm_cond', 'scope_dim_cd', 'ALM_SCOPE_DIM', 'N')
ON CONFLICT DO NOTHING;

COMMIT;
