-- =====================================================================================
--  V75 되돌리기 — 용어 분류(domain) 복원 · 용어별 데이터 접근 항목 제거 (2026-10-03)
--
--  기록표(ax.tb_mig_v75_gls_domain_bak · ax.tb_mig_v75_gls_term_domain_bak)에서
--   1. ax.tb_gls_domain 을 V75 직전 구조(V66 의 data_field_key · FK 포함) · 번호 · 값 그대로 되살리고
--   2. ax.tb_gls_term.domain_id 를 되살려 용어별 분류를 되돌린 뒤 NOT NULL · FK 를 건다.
--      V75 뒤에 새로 만든 용어(기록표에 없음)는 분류 「기타」 로 넣는다(없으면 만든다). 건수는 NOTICE.
--   3. ax.tb_gls_term.data_field_key(FK 포함)를 지운다. 가림은 분류 단위(V66)로 돌아간다.
--      V75 뒤에 용어별로 바꾼 가림 표시가 분류 값과 다르면 그 차이는 사라진다 — 건수를 NOTICE 로 알린다.
--  기록표는 지우지 않는다(다시 V75 를 적용하면 덮어쓴다).
--
--  [API 를 먼저 옛 코드로 내린다]
--  새 API 는 term.data_field_key 를 읽는다. 이 파일 뒤에는 용어 조회가 500 이 된다.
--
--  [적용]
--  psql -U <user> -d <db> -v ON_ERROR_STOP=1 -f rollback/V75__down.sql
--  두 번 실행해도 안전하다(tb_gls_term.domain_id 가 이미 있으면 건너뜀).
-- =====================================================================================

BEGIN;

DO $$
DECLARE
    v_domain   integer;
    v_new_term integer;
    v_diff     integer;
    v_etc      integer;
BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.columns
                WHERE table_schema = 'ax' AND table_name = 'tb_gls_term' AND column_name = 'domain_id') THEN
        RAISE NOTICE 'V75 down: 이미 되돌림 (tb_gls_term.domain_id 있음) — 건너뜀';
        RETURN;
    END IF;
    IF to_regclass('ax.tb_mig_v75_gls_domain_bak') IS NULL OR to_regclass('ax.tb_mig_v75_gls_term_domain_bak') IS NULL THEN
        RAISE EXCEPTION 'V75 down: 기록표가 없어 되돌릴 수 없습니다';
    END IF;

    -- 1. 분류 표
    CREATE TABLE ax.tb_gls_domain (
        domain_id      integer GENERATED BY DEFAULT AS IDENTITY,
        domain_nm      varchar(50) NOT NULL,
        sort_seq       smallint DEFAULT 0 NOT NULL,
        use_flg        common.d_yn DEFAULT 'Y'::bpchar NOT NULL,
        data_field_key varchar(30),
        CONSTRAINT tb_gls_domain_pkey PRIMARY KEY (domain_id),
        CONSTRAINT uq_tb_gls_domain_nm UNIQUE (domain_nm),
        CONSTRAINT fk_gls_domain_data_field FOREIGN KEY (data_field_key) REFERENCES ax.tb_sys_data_field (field_key)
    );
    INSERT INTO ax.tb_gls_domain (domain_id, domain_nm, sort_seq, use_flg, data_field_key)
    OVERRIDING SYSTEM VALUE
    SELECT domain_id, domain_nm, sort_seq, use_flg, data_field_key FROM ax.tb_mig_v75_gls_domain_bak ORDER BY domain_id;
    GET DIAGNOSTICS v_domain = ROW_COUNT;
    PERFORM setval(pg_get_serial_sequence('ax.tb_gls_domain', 'domain_id'),
                   greatest((SELECT max(domain_id) FROM ax.tb_gls_domain), 1));

    -- 2. 용어별 분류
    ALTER TABLE ax.tb_gls_term ADD COLUMN domain_id integer;
    UPDATE ax.tb_gls_term t SET domain_id = b.domain_id
      FROM ax.tb_mig_v75_gls_term_domain_bak b
     WHERE b.term_id = t.term_id;

    SELECT count(*) INTO v_new_term FROM ax.tb_gls_term WHERE domain_id IS NULL;
    IF v_new_term > 0 THEN
        INSERT INTO ax.tb_gls_domain (domain_nm, sort_seq, use_flg) VALUES ('기타', 9999, 'Y')
        ON CONFLICT (domain_nm) DO NOTHING;
        SELECT domain_id INTO v_etc FROM ax.tb_gls_domain WHERE domain_nm = '기타';
        UPDATE ax.tb_gls_term SET domain_id = v_etc WHERE domain_id IS NULL;
    END IF;

    ALTER TABLE ax.tb_gls_term ALTER COLUMN domain_id SET NOT NULL;
    ALTER TABLE ax.tb_gls_term
        ADD CONSTRAINT tb_gls_term_domain_id_fkey FOREIGN KEY (domain_id) REFERENCES ax.tb_gls_domain (domain_id);

    -- 3. 용어별 가림 표시 제거 — 분류 값과 다른 용어 수를 알린다
    SELECT count(*) INTO v_diff
      FROM ax.tb_gls_term t JOIN ax.tb_gls_domain d ON d.domain_id = t.domain_id
     WHERE t.data_field_key IS DISTINCT FROM d.data_field_key;
    ALTER TABLE ax.tb_gls_term DROP CONSTRAINT IF EXISTS fk_gls_term_data_field;
    ALTER TABLE ax.tb_gls_term DROP COLUMN IF EXISTS data_field_key;

    RAISE NOTICE 'V75 down: 분류 % 건 복원, 기록표에 없는 용어 % 건은 「기타」, 분류 값과 달랐던 용어 가림 % 건은 분류 값으로 돌아감',
        v_domain, v_new_term, v_diff;
END $$;

COMMENT ON TABLE ax.tb_gls_domain IS
  '용어 분류/도메인 — 회사/고객사, 품질관리, 불량유형 등. data_field_key 가 있으면 그 데이터 접근 권한이 있어야 그 분류 용어를 봄';
COMMENT ON COLUMN ax.tb_gls_domain.domain_id IS '용어 분류 대리키';
COMMENT ON COLUMN ax.tb_gls_domain.domain_nm IS '분류명. 용어 사전 관리 화면의 분류 선택지가 이 값. 같은 화면의 「분류」 열과 공식 용어 등록 폼의 분류 선택';
COMMENT ON COLUMN ax.tb_gls_domain.sort_seq IS '분류 선택지 표시 순서';
COMMENT ON COLUMN ax.tb_gls_domain.use_flg IS '사용 유무 (Y/N). N 이면 분류 선택지에서 빠짐';
COMMENT ON COLUMN ax.tb_gls_domain.data_field_key IS
  '이 분류 용어를 볼 때 필요한 데이터 접근 항목(ax.tb_sys_data_field). 권한이 없으면 용어를 「비공개 용어」 로 가리고 덕반장 AI [용어] 블록에서 뺌. NULL 이면 모두 열람. 예: 고객사 계열 분류 = customer';
COMMENT ON COLUMN ax.tb_gls_term.domain_id IS '소속 분류 (ax.tb_gls_domain). 용어 사전 관리 화면의 「분류」 열에 분류명으로 표시';
COMMENT ON TABLE ax.tb_gls_term IS '공식 용어 — 보고서·리포트 출력 표기 기준. 통합관리자만 등록·수정';

COMMIT;
